#!/usr/bin/env python3
"""Convert the Markdown vault to Neo4j graph data.

Default behavior writes a Cypher file. Optional --execute imports directly if the
neo4j Python driver is installed and a Neo4j server is reachable.

Examples:
  python tools/kb_to_neo4j.py --vault . --out out/windows_app_baseline.cypher --debug
  python tools/kb_to_neo4j.py --vault . --execute --uri bolt://localhost:7687 --user neo4j --password password --debug
"""
from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path
from typing import Any

try:
    from .wabk_common import (
        Document,
        build_title_index,
        configure_logging,
        json_dumps,
        load_documents,
        resolve_link,
    )
except ImportError:  # allow running as: python tools/kb_to_neo4j.py
    from wabk_common import (
        Document,
        build_title_index,
        configure_logging,
        json_dumps,
        load_documents,
        resolve_link,
    )

LOG = logging.getLogger("wabk.neo4j")


def cypher_escape(value: Any) -> str:
    return json.dumps(value, ensure_ascii=False)


def make_node_cypher(doc: Document) -> str:
    labels = ["KbDocument"]
    type_label = ''.join(part.capitalize() for part in str(doc.type).replace('-', '_').split('_') if part)
    if type_label:
        labels.append(type_label)
    props = {
        "id": doc.id,
        "path": doc.path,
        "title": doc.title,
        "type": doc.type,
        "os": doc.os,
        "name": doc.name,
        "frontmatter_json": json_dumps(doc.frontmatter),
        "body_text": doc.body_text,
        "sha256": doc.sha256,
        "mtime": doc.mtime,
        "tags": doc.tags,
        "aliases": doc.aliases,
        "vendor": doc.frontmatter.get("vendor") or doc.frontmatter.get("vendor_name"),
        "risk_level": doc.frontmatter.get("risk_level"),
        "confidence": doc.frontmatter.get("confidence"),
    }
    prop_text = ", ".join(f"{k}: {cypher_escape(v)}" for k, v in props.items())
    return f"MERGE (n:{':'.join(labels)} {{id: {cypher_escape(doc.id)}}}) SET n += {{{prop_text}}};"


def make_link_cypher(source_id: str, target_id: str, occ: dict[str, Any]) -> str:
    props = {
        "raw_link": occ.get("raw_link"),
        "target_text": occ.get("target_text"),
        "context_heading": occ.get("context_heading"),
        "line_no": occ.get("line_no"),
        "line_text": occ.get("line_text"),
    }
    prop_text = ", ".join(f"{k}: {cypher_escape(v)}" for k, v in props.items())
    return (
        f"MATCH (a:KbDocument {{id: {cypher_escape(source_id)}}}), (b:KbDocument {{id: {cypher_escape(target_id)}}}) "
        f"MERGE (a)-[r:LINKS_TO {{raw_link: {cypher_escape(occ.get('raw_link'))}, line_no: {cypher_escape(occ.get('line_no'))}}}]->(b) "
        f"SET r += {{{prop_text}}};"
    )


def make_unresolved_link_cypher(source_id: str, occ: dict[str, Any]) -> str:
    target_key = occ.get("target_text") or ""
    unresolved_id = "unresolved:" + target_key
    props = {
        "id": unresolved_id,
        "name": target_key,
        "type": "unresolved_link_target",
        "title": target_key,
    }
    prop_text = ", ".join(f"{k}: {cypher_escape(v)}" for k, v in props.items())
    rel_props = {
        "raw_link": occ.get("raw_link"),
        "target_text": target_key,
        "context_heading": occ.get("context_heading"),
        "line_no": occ.get("line_no"),
        "line_text": occ.get("line_text"),
        "resolved": False,
    }
    rel_prop_text = ", ".join(f"{k}: {cypher_escape(v)}" for k, v in rel_props.items())
    return (
        f"MERGE (b:KbDocument:UnresolvedTarget {{id: {cypher_escape(unresolved_id)}}}) SET b += {{{prop_text}}};\n"
        f"MATCH (a:KbDocument {{id: {cypher_escape(source_id)}}}), (b:KbDocument {{id: {cypher_escape(unresolved_id)}}}) "
        f"MERGE (a)-[r:LINKS_TO {{raw_link: {cypher_escape(occ.get('raw_link'))}, line_no: {cypher_escape(occ.get('line_no'))}}}]->(b) "
        f"SET r += {{{rel_prop_text}}};"
    )


def build_cypher(docs: list[Document], include_unresolved: bool = True) -> str:
    LOG.info("build Cypher for docs=%d", len(docs))
    title_index = build_title_index(docs)
    lines: list[str] = []
    lines.append("// 终端应用安全基线画像库 Neo4j import generated by tools/kb_to_neo4j.py")
    lines.append("CREATE CONSTRAINT kb_document_id IF NOT EXISTS FOR (n:KbDocument) REQUIRE n.id IS UNIQUE;")
    lines.append("CREATE INDEX kb_document_title IF NOT EXISTS FOR (n:KbDocument) ON (n.title);")
    lines.append("CREATE INDEX kb_document_type IF NOT EXISTS FOR (n:KbDocument) ON (n.type);")
    lines.append("CREATE INDEX kb_document_name IF NOT EXISTS FOR (n:KbDocument) ON (n.name);")
    lines.append("")
    for doc in docs:
        LOG.debug("emit node path=%s type=%s title=%s", doc.path, doc.type, doc.title)
        lines.append(make_node_cypher(doc))
    lines.append("")
    resolved = 0
    unresolved = 0
    for doc in docs:
        for occ in doc.link_occurrences:
            target_doc_id = resolve_link(occ["target_text"], title_index)
            if target_doc_id:
                resolved += 1
                lines.append(make_link_cypher(doc.id, target_doc_id, occ))
            elif include_unresolved:
                unresolved += 1
                lines.append(make_unresolved_link_cypher(doc.id, occ))
    LOG.info("Cypher link stats resolved=%d unresolved=%d", resolved, unresolved)
    return "\n".join(lines) + "\n"


def write_cypher(vault: Path, out: Path, include_unresolved: bool) -> str:
    docs = load_documents(vault)
    cypher = build_cypher(docs, include_unresolved=include_unresolved)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(cypher, encoding="utf-8")
    LOG.info("Cypher file written: %s bytes=%d", out, out.stat().st_size)
    return cypher


def execute_cypher(cypher_text: str, uri: str, user: str, password: str, database: str | None, batch_size: int = 500) -> None:
    try:
        from neo4j import GraphDatabase  # type: ignore
    except Exception as exc:  # pragma: no cover
        raise RuntimeError("neo4j Python driver is not installed. Run: pip install neo4j") from exc
    statements = [stmt.strip() for stmt in cypher_text.split(";\n") if stmt.strip()]
    LOG.info("execute Cypher statements=%d uri=%s database=%s", len(statements), uri, database or "default")
    driver = GraphDatabase.driver(uri, auth=(user, password))
    try:
        with driver.session(database=database) if database else driver.session() as session:
            for i in range(0, len(statements), batch_size):
                batch = statements[i:i + batch_size]
                LOG.debug("execute batch start=%d size=%d", i, len(batch))
                for stmt in batch:
                    session.run(stmt).consume()
        LOG.info("Neo4j import finished")
    finally:
        driver.close()


def parse_args(argv: list[str]) -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Convert Windows App Security Baseline Markdown vault to Neo4j Cypher/import.")
    p.add_argument("--vault", default=".", help="Obsidian vault root path")
    p.add_argument("--out", default="out/windows_app_baseline.cypher", help="Output Cypher file path")
    p.add_argument("--no-unresolved", action="store_true", help="Do not create placeholder nodes for unresolved Obsidian links")
    p.add_argument("--execute", action="store_true", help="Execute generated Cypher against Neo4j")
    p.add_argument("--uri", default="bolt://localhost:7687", help="Neo4j Bolt URI")
    p.add_argument("--user", default="neo4j", help="Neo4j username")
    p.add_argument("--password", default=None, help="Neo4j password")
    p.add_argument("--database", default=None, help="Neo4j database name")
    p.add_argument("--batch-size", type=int, default=500, help="Execution batch size")
    p.add_argument("--debug", action="store_true", help="Enable debug logs")
    p.add_argument("--log-file", default=None, help="Write logs to file as well as stderr")
    return p.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    configure_logging(args.debug, args.log_file)
    cypher = write_cypher(Path(args.vault), Path(args.out), include_unresolved=not args.no_unresolved)
    if args.execute:
        if not args.password:
            raise SystemExit("--execute requires --password")
        execute_cypher(cypher, args.uri, args.user, args.password, args.database, args.batch_size)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
